# Generated by Django 4.1 on 2024-10-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_created_at_post_created_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
